version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    environment:
      - PORT=3333
      - MONGO_URL=mongodb://mongo:27017/users

volumes:
  mongo-data:
